# Generated by Django 2.0.4 on 2018-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20180528_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
