# Generated by Django 2.0.4 on 2018-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20180528_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
