# Generated by Django 2.0.4 on 2018-05-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comments_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comments.Comments'),
        ),
    ]
