# Generated by Django 2.0.4 on 2018-12-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20180530_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_time']},
        ),
    ]
