# Generated by Django 2.0.4 on 2018-05-27 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
