# Generated by Django 2.0.4 on 2018-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='toc',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
