"""
Django settings for AngelBang project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import socket
from datetime import datetime
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b=mqh@wih4k36qw98^n&27@h1j$ms@)m@46w@uu*5dvtfp!hsd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.angelbang.cn']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'haystack',
    'markdownx',
    'comments',
    'ckeditor',
]

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'blog.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AngelBang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AngelBang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'angelbang',
        'USER':'root',
        'PASSWORD':'root',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers':True,
    'formatters':{#日志格式
        'standard':{
            'format':'%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d]'
                     ' [%(module)s:%(funcName)s] [%(levelname)s] - %(message)s'
        },
    },
    'filters':{#过滤器
    },
    'handlers':{#处理器
        'null':{
            'level':'DEBUG',
            'class':'logging.NullHandler',
        },
        'debug':{#输出到文件
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename':os.path.join(BASE_DIR,"log", "debug.log"),#日志输出文件
            'maxBytes':1024*1024*5,#文件大小
            'backupCount':5,#备份数
            'formatter':'standard',#使用哪种formatters日志格式
        },
        'console':{#输出到控制台
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter':'standard',
        },
        'mail_admins':{
            'level':'ERROR',
            'class':'django.utils.log.AdminEmailHandler',
            'include_html':True,
        }
    },
    'loggers':{#logging管理器
        'django':{
            'handlers':['console'],
            'level':'DEBUG',
            'propagate':False,
        },
        'django.request':{
            'handlers':['debug', 'mail_admins'],
            'level':'ERROR',
            'propagate':True,
        },
        # 对于不再Allowed_hosts 中的请求不发送报错邮件
        'django.security.DisallowedHost':{
            'handlers':['null'],
            'propaget':False,
        },
    },
}

# 邮箱设置
ADMINS = (
    ('angelbang', 'igoab1990@163.com'),
)

# 非空链接，却发生404错误，发送通知MANAGERS
SEND_BROKENT_LINK_EMAILS = True
MANAGERS = ADMINS

#Email 设置
EMAIL_BACKENT = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'#163SMTP服务器
EMAIL_PORT = 25#端口
EMAIL_HOST_USER = 'igongaobo@163.com'#账号
EMAIL_HOST_PASSWORD = 'woaifml1314' #密码
EMAIL_USE_TLS = True #开启安全链接
DEFAULT_FROM_EMAIL = SERVER_EMAIL = EMAIL_HOST_USER #设置发件人

# 图片
MEDIA_URL = '/media/'
MARKDOWNX_MEDIA_PATH = datetime.now().strftime('markdownx/%Y/%m/%d')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MARKDOWNX_UPLOAD_MAX_SIZE= 50 * 1024 * 1024
MARKDOWNX_IMAGE_MAX_SIZE = { 'size': (500, 500),
          'quality': 90,
          'upscale':True}

# markdown setttings
MARKDOWNX_MARKDOWN_EXTENSIONS = {'markdown.extensions.extra', 'markdown.extensions.codehilite'}
MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {'':'',}

# 配置ckeditor
CKEDITOR_CONFIGS={
    'comment_ckeditor':{
        'toolbar':'custom',
        'toolbar_custom':[
            ['Bold','Italic','Underline','Strike','Subscript', 'Superscript'],
            ['TextColor','BGColor','RemoveFormat'],
            ['NumberedList','BulletedList'],
            ['Link', 'Unlink'],
            ['Smiley', 'SpecialChar','Blockquote'],
        ],
        'width':'auto',
        'height':'180',
        'tabSapces':4,
        'removePlugins':'elementspath',
        'resize_enable':False,
    }
}
